2013/08/04 21:40:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:41:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 21:42:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii/default/login
---
2013/08/04 22:28:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:29:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:29:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:29:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:30:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:31:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:32:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:33:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:33:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:34:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 22:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=gii
---
2013/08/04 23:05:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/page?view=about
---
2013/08/04 23:05:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/page/view/about
---
2013/08/04 23:05:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/contact
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:06:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/contact
---
2013/08/04 23:06:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/contact
---
2013/08/04 23:06:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/contact
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:07:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:07:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/
---
2013/08/04 23:07:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:07:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:07:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/
---
2013/08/04 23:07:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:07:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:07:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/
---
2013/08/04 23:07:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/contact
HTTP_REFERER=http://localhost/yiitest/site/page/view/about
---
2013/08/04 23:07:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/login
HTTP_REFERER=http://localhost/yiitest/site/contact
---
2013/08/04 23:08:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:08:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/contact
HTTP_REFERER=http://localhost/yiitest/site/page/view/about
---
2013/08/04 23:08:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/login
HTTP_REFERER=http://localhost/yiitest/site/contact
---
2013/08/04 23:08:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/contact
HTTP_REFERER=http://localhost/yiitest/site/login
---
2013/08/04 23:08:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/index
HTTP_REFERER=http://localhost/yiitest/site/page/view/about
---
2013/08/04 23:08:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/site/contact
HTTP_REFERER=http://localhost/yiitest/site/index
---
2013/08/04 23:08:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "<controller>/index".' in C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('<controller>/in...')
#1 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index
---
2013/08/04 23:24:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yiitest\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yiitest\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\yiitest\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'customers'' in C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yiitest\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yiitest\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\yiitest\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'customers'' in C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yiitest\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yiitest\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\yiitest\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'customers'' in C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yiitest\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yiitest\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\yiitest\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'customers'' in C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yiitest\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yiitest\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yiitest\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\yiitest\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:52 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected. The SQL statement executed was: SHOW TABLES.
in C:\xampp\htdocs\yiitest\index.php (13)
2013/08/04 23:24:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected. The SQL statement executed was: SHOW TABLES' in C:\xampp\htdocs\yiitest\framework\db\CDbCommand.php:541
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbCommand.php(454): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yiitest\framework\db\schema\mysql\CMysqlSchema.php(251): CDbCommand->queryColumn()
#2 C:\xampp\htdocs\yiitest\framework\db\schema\CDbSchema.php(139): CMysqlSchema->findTableNames('')
#3 C:\xampp\htdocs\yiitest\framework\db\schema\CDbSchema.php(122): CDbSchema->getTableNames('')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\views\index.php(79): CDbSchema->getTables()
#5 C:\xampp\htdocs\yiitest\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yiitest\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yiitest\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yiitest\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(72): CController->render('index', Array)
#10 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#16 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#17 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:53 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected. The SQL statement executed was: SHOW TABLES.
in C:\xampp\htdocs\yiitest\index.php (13)
2013/08/04 23:24:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected. The SQL statement executed was: SHOW TABLES' in C:\xampp\htdocs\yiitest\framework\db\CDbCommand.php:541
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbCommand.php(454): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yiitest\framework\db\schema\mysql\CMysqlSchema.php(251): CDbCommand->queryColumn()
#2 C:\xampp\htdocs\yiitest\framework\db\schema\CDbSchema.php(139): CMysqlSchema->findTableNames('')
#3 C:\xampp\htdocs\yiitest\framework\db\schema\CDbSchema.php(122): CDbSchema->getTableNames('')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\views\index.php(79): CDbSchema->getTables()
#5 C:\xampp\htdocs\yiitest\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yiitest\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yiitest\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yiitest\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(72): CController->render('index', Array)
#10 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#16 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#17 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
2013/08/04 23:24:53 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected. The SQL statement executed was: SHOW TABLES.
in C:\xampp\htdocs\yiitest\index.php (13)
2013/08/04 23:24:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected. The SQL statement executed was: SHOW TABLES' in C:\xampp\htdocs\yiitest\framework\db\CDbCommand.php:541
Stack trace:
#0 C:\xampp\htdocs\yiitest\framework\db\CDbCommand.php(454): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yiitest\framework\db\schema\mysql\CMysqlSchema.php(251): CDbCommand->queryColumn()
#2 C:\xampp\htdocs\yiitest\framework\db\schema\CDbSchema.php(139): CMysqlSchema->findTableNames('')
#3 C:\xampp\htdocs\yiitest\framework\db\schema\CDbSchema.php(122): CDbSchema->getTableNames('')
#4 C:\xampp\htdocs\yiitest\framework\gii\generators\model\views\index.php(79): CDbSchema->getTables()
#5 C:\xampp\htdocs\yiitest\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yiitest\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yiitest\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yiitest\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 C:\xampp\htdocs\yiitest\framework\gii\CCodeGenerator.php(72): CController->render('index', Array)
#10 C:\xampp\htdocs\yiitest\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#11 C:\xampp\htdocs\yiitest\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yiitest\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yiitest\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yiitest\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#16 C:\xampp\htdocs\yiitest\framework\base\CApplication.php(169): CWebApplication->processRequest()
#17 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yiitest/gii/model
HTTP_REFERER=http://localhost/yiitest/gii
---
